import { z } from "zod"
import { durationWeekOptions, programTypeOptions } from "@/types/campfit"

const NullableStringSchema = z.string().nullable()
const NullableNumberSchema = z.number().nullable()

export const ProgramRowSchema = z.object({
  id: z.string(),
  name: z.string().nullable(),
  title: z.string().nullable(),
  slug: z.string().nullable(),
  program_type: NullableStringSchema,
  program_focus: NullableStringSchema,
  host_institution: NullableStringSchema,
  organizer: NullableStringSchema,
  detailed_description: NullableStringSchema,
  short_description: NullableStringSchema,
  subtitle: NullableStringSchema,
  price_details: NullableStringSchema,
  display_price: NullableStringSchema,
  minimum_price: z.union([z.string(), z.number()]).nullable(),
  minimum_price_currency: NullableStringSchema,
  minimum_price_value: NullableNumberSchema,
  base_price_currency: NullableStringSchema,
  base_price_value: NullableNumberSchema,
  location_country: NullableStringSchema,
  location_city: NullableStringSchema,
  country: NullableStringSchema,
  city: NullableStringSchema,
  target_age: NullableStringSchema,
  age_min: NullableNumberSchema,
  age_max: NullableNumberSchema,
  duration: NullableStringSchema,
  duration_options: NullableStringSchema,
  minimum_duration: NullableStringSchema,
  program_languages: NullableStringSchema,
  language_level: NullableStringSchema,
  group_composition: NullableStringSchema,
  parent_participation_type: NullableStringSchema,
  accommodation_type: NullableStringSchema,
  care_level: NullableStringSchema,
  care_types: NullableStringSchema,
  local_presence: z.boolean().nullable(),
  coverage_schedule: NullableStringSchema,
  emergency_support: z.boolean().nullable(),
  languages_supported: NullableStringSchema,
  onsite_manager: z.boolean().nullable(),
  local_meeting_available: z.boolean().nullable(),
  item_accommodation: NullableStringSchema,
  item_supervision_support: NullableStringSchema,
  item_transportation: NullableStringSchema,
  item_education_program: NullableStringSchema,
  items_notes: NullableStringSchema,
  not_included: z.array(z.string()).nullable(),
  detail_payload: z.unknown().nullable(),
  status: NullableStringSchema,
  visible: z.boolean().nullable(),
  is_listed: z.boolean().nullable(),
})

export const PriceOptionRowSchema = z.object({
  program_id: z.string(),
  duration_weeks: z.number().nullable(),
  currency: z.string().nullable(),
  price_value: z.number().nullable(),
  status: z.string().nullable(),
})

export const ProgramProfileRowSchema = z.object({
  program_id: z.string(),
  program_name: z.string().nullable(),
  country: z.string().nullable(),
  city: z.string().nullable(),
  program_type: z.enum(programTypeOptions).exclude(["unsure"]),
  age_min: z.number().nullable(),
  age_max: z.number().nullable(),
  budget_min_krw: z.number().nullable(),
  budget_max_krw: z.number().nullable(),
  duration_weeks: z.array(z.enum(durationWeekOptions)).nullable(),
  korean_manager: z.boolean().nullable(),
  parent_accompanied: z.boolean().nullable(),
  korean_dorm_option: z.boolean().nullable(),
  beginner_class: z.boolean().nullable(),
  buddy_system: z.boolean().nullable(),
  early_adaptation_support: z.boolean().nullable(),
  daily_parent_report: z.boolean().nullable(),
  low_pressure_speaking_environment: z.boolean().nullable(),
  small_group_care: z.boolean().nullable(),
  english_exposure: z.number().nullable(),
  boarding_independence: z.number().nullable(),
  academic_intensity: z.number().nullable(),
  foreign_peer_interaction: z.number().nullable(),
  parent_separation: z.number().nullable(),
  traits: z.array(z.string()).nullable(),
  active: z.boolean().nullable(),
})

export type ProgramRow = z.infer<typeof ProgramRowSchema>
export type PriceOptionRow = z.infer<typeof PriceOptionRowSchema>
export type ProgramProfileRow = z.infer<typeof ProgramProfileRowSchema>
